app:
  name: My app
  description: Welcome to ${app.name}

my:
  greeting: Hello World
  list:
    values: One,Tow,Three

management.endpoints.web.exposure.include: '*'

spring.application.name: spring-cloud-online-config-server
#  profiles:
#    active: dev